export const cartTypes = {
  ADD_PRODUCT: "ADD_PRODUCT",
  INITIALIZE_APP_CART: "INITIALIZE_APP_CART",
  LOAD_CART_DATA: "LOAD_CART_DATA",
  CLEAR_CART: "CLEAR_CART",
};

export const userTypes = {
  LOGIN_START: "LOGIN_START",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  INITIALIZE_APP_USER: "INITIALIZE_APP_USER",
  LOAD_USER_DATA: "LOAD_USER_DATA",
  DELETE_USER: "DELETE_USER",
};
